@startuml
' Activer les lignes orthogonales
'skinparam linetype ortho
left to right direction
actor Utilisateur
actor Administrateur
actor WebMaster

Utilisateur -- (Voir produits)
Utilisateur -- (Contacter webmaster)
Utilisateur -- (Passer commande)
Utilisateur -- (Modifier le profil)
Utilisateur -- (Noter entreprise)
Utilisateur -- (Gestion compte création/auth/connexion)

(liker produit)..u..>(Voir produits):extends
(liker produit)..u..>(Gestion compte création/auth/connexion):include

(Contacter webmaster)..u..>(Gestion compte création/auth/connexion):include
(Passer commande)..u..>(Gestion compte création/auth/connexion):include
(Noter entreprise)..u..>(Gestion compte création/auth/connexion):include


Administrateur -- (Gérer les profils utilisateurs)
Administrateur -- (Modifier BD produit)

(Gérer les profils utilisateurs)..l..>(Gestion compte création/auth/connexion):include
(Gérer les profils utilisateurs)<....(Reinitialiser mdp utilisateur):extends
(Gérer les profils utilisateurs)<....(Valider compte):extends
(Gérer les profils utilisateurs)<....(Radier compte):extends
(Gérer les profils utilisateurs)<....(Modifier compte):extends

(Modifier BD produit)<....(Augmenter stock produit):extends
(Modifier BD produit)<....(Proposer reduc produit):extends
(Modifier BD produit)<....(Ajouter nouveau produit):extends
(Modifier BD produit)<....(Supprimer produit):extends
(Modifier BD produit)<....(Modifier produit):extends 
'(Passer une commande) --> (Visualiser les détails d'un produit) : extends

(WebMaster)--(Repondre utilisateur)



@enduml