@startuml Action produit utilisateur

":Utilisateur" -> SiteWeb: consulter produit
activate SiteWeb

SiteWeb --> ":Utilisateur": page produit

alt achat
":Utilisateur" -> SiteWeb: acheter produit
SiteWeb -> ":Produit": mise à jour stock
activate ":Produit"
return
SiteWeb --> ":Utilisateur": mise à jour page produit
else like
":Utilisateur" -> SiteWeb: like produit
SiteWeb -> ":Produit": ajoutLike
activate ":Produit"
return
SiteWeb --> ":Utilisateur": mise à jour page produit
end

@enduml