@startuml Création Profil

":Utilisateur" -> SiteWeb: création profil
activate "SiteWeb"

SiteWeb -> "InstanceBD:Utilisateur": création profil

activate "InstanceBD:Utilisateur"

deactivate "InstanceBD:Utilisateur"

return page Connexion

@enduml