@startuml Modifier Profil

":Utilisateur" -> SiteWeb: consulter profil
activate SiteWeb

SiteWeb --> ":Utilisateur": page profil

":Utilisateur" -> SiteWeb: modifier profil

SiteWeb -> "Base de données": modifier profil

activate "Base de données"

"Base de données" -> "Base de données": modifier profil

return nouveau profil

SiteWeb --> ":Utilisateur": mise à jour page profil

@enduml