@startuml Connexion administrateur

loop tentatives <= 5
":Administrateur" -> SiteWeb: authentification
activate SiteWeb
SiteWeb -> ":ControleurUtilisateur": authentifier
activate ":ControleurUtilisateur"
return réponse
alt connexion réussie
    SiteWeb -> ":Administrateur": authentification acceptée
else connexion échouée && tentatives < 5
    SiteWeb -> ":Administrateur": authentification refusée
else connexion échouée && tentatives = 5
    SiteWeb -> ":Administrateur": connexion bloquée
end
end
@enduml