@startuml Gerer Compte

alt modifier produit
":Administrateur" -> SiteWeb: modifier produit
activate SiteWeb
SiteWeb -> ":ControleurProduit": modifier produit
activate ":ControleurProduit"
":ControleurProduit" -> "Base de données": modifierProduit
activate "Base de données"
return
deactivate ":ControleurProduit"
else augmenter stock produit
":Administrateur" -> SiteWeb: augmenter stock produit
SiteWeb -> ":ControleurProduit": augmenter stock produit
activate ":ControleurProduit"
":ControleurProduit" -> "Base de données": modifierProduit
activate "Base de données"
return
deactivate ":ControleurProduit"
else reduction produit
":Administrateur" -> SiteWeb: reduction produit
SiteWeb -> ":ControleurProduit": reduction produit
activate ":ControleurProduit"
":ControleurProduit" -> "Base de données": appliquerReduction
activate "Base de données"
return
deactivate ":ControleurProduit"
else nouveau produit
":Administrateur" -> SiteWeb: nouveau produit
SiteWeb -> ":ControleurProduit": nouveau produit
activate ":ControleurProduit"
":ControleurProduit" -> "Base de données": ajouterProduit
activate "Base de données"
return
deactivate ":ControleurProduit"
else supprimer produit
":Administrateur" -> SiteWeb: supprimer produit

SiteWeb -> ":ControleurProduit": supprimer produit
activate ":ControleurProduit"
":ControleurProduit" -> "Base de données": getStock
activate "Base de données"
return stock

alt stock = 0
":ControleurProduit" -> "Base de données": supprimerProduit
activate "Base de données"
return
":ControleurProduit" --> SiteWeb
else stock > 0
return erreur
end
end

@enduml