@startuml Accueil Utilisateur

 group Connexion
":Utilisateur" -> SiteWeb: connexion
activate SiteWeb
|||
 end

SiteWeb --> ":Utilisateur": page accueil

loop connecté
alt page produit
 group ActionProduit
":Utilisateur" -> SiteWeb: action produit
|||
end
else ModifierProfil
 group ModifierProfil
":Utilisateur" -> SiteWeb: modifier profil
|||
end
else noter
":Utilisateur" -> SiteWeb: noter sur 10 étoiles
else contacter
":Utilisateur" -> SiteWeb: envoyer message au Webmaster
SiteWeb -> ":Webmaster": envoyer message 
end
end

":Utilisateur" -> SiteWeb: déconnexion
deactivate SiteWeb



@enduml