@startuml Connexion utilisateur

alt pas de compte
 group CreationProfil
":Utilisateur" -> SiteWeb: création profil
activate SiteWeb
|||
 end
end

loop tentatives <= 5
":Utilisateur" -> SiteWeb: authentification

SiteWeb -> ":ControleurUtilisateur": authentifier
activate ":ControleurUtilisateur"
return réponse
alt connexion réussie
    SiteWeb -> ":Utilisateur": authentification acceptée
else connexion échouée && tentatives < 5
    SiteWeb -> ":Utilisateur": authentification refusée
else connexion échouée && tentatives = 5
    SiteWeb -> ":Utilisateur": connexion bloquée
end
end
@enduml